on: push
jobs:
  first-job:
    runs-on: windows-latest
    steps: 
      - run: node --version
      - run: npm --version

  second-job:
    runs-on: ubuntu-22.04
    steps:
      - run: node --version
      - run: npm --version
